{% set name = "satmad" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b31e4b10d3aa3bfa8bff231b85b9f331a594006e48e45249c49cbb11a366fe5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - flit-core
    - pip
    - python

  run:
    - astropy
    - matplotlib-base
    - numpy
    - portion
    - python
    - scipy
    - sgp4

test:
  imports:
    - satmad
    - satmad.coordinates
    - satmad.coordinates.tests
    - satmad.propagation
    - satmad.propagation.tests
    - satmad.tests
    - satmad.utils
    - satmad.utils.tests
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/egemenimre/satmad/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.rst
  summary: 'SatMAD: Satellite Mission Analysis and Design for Python'
  doc_url: https://satmad.readthedocs.io/
  dev_url: https://github.com/egemenimre/satmad/

  description: |
    SatMAD is an open source Python package, aiming at providing the base functionality to solve 
    satellite mission analysis and design as well as orbital mechanics problems with enough 
    precision and performance to be used in the design and operation of real satellites. 
    The target audience is academics and amateur satellite community, including Cubesats 
    (and anyone else who might be interested).
extra:
  recipe-maintainers:
    - egemenimre
